<?php
require_once "Controllers/Controller.php";
require_once "Controllers/StoreController.php";
require_once "Controllers/TestController.php";
require_once "Controllers/ConnectionController.php";
require_once "Controllers/VerifConnectionController.php";
require_once "Controllers/InscriptionController.php";
require_once "Controllers/VerifInscriptionController.php";
require_once "Controllers/ShopController.php";
require_once "Controllers/DisconnectController.php";
require_once "Controllers/ManageCategoriesController.php";
require_once "Controllers/ManageAddReferenceController.php";
require_once "Controllers/VerifAddDomainProductController.php";
require_once "Controllers/ManageAllProductController.php";
require_once "Controllers/ManageAllReferenceController.php";
require_once "Controllers/TraderAddOfferController.php";
require_once "Controllers/TranslationController.php";
require_once "Router.php";
require_once "utils.php";